### ISSUE TITLE
Problem running code

### ISSUE THREAD

**Issue by kikesfunspace** [vil/H4X-Tools#17]
I am currently trying to run the cloned code on my Terminal using Py 3.12.0 and at first it was telling me there was a problem "building the wheel for aiohttp" (I think I had that fixed by installing the aiohttp 3.9 beta) but now it is saying "Failed to execute script 'h4x tools' due to unhandled exception! "  What should I do?

**Comment by V1li** [comment]
Yeah the new Python update broke everything again. There is nothing I can do other than wait for aiohttp to update. 

https://github.com/aio-libs/aiohttp/issues/7816

**Comment by vil** [comment]
@aio-libs fixed aiohttp and H4X-Tools now builds in Python 3.12 if you have `python-dev` on Windows or `python-devel` on Linux installed.
